config:
  experiment_name: "old_man"
  block: "output_block_11" # the module name of the visualized features (e.g. "output_block_4", "input_block_7").
  experiments_fit: # the list of the experiments to visualize the features for
    - "old_man"
  experiments_transform: # the list of the experiments used for calculating the principal components
    - "old_man"