pip install omegaconf
pip install einops
pip install lpips
pip install pytorch_lightning
pip install git+https://github.com/openai/CLIP.git
pip install Lightning
pip install taming-transformers-rom1504
pip install transformers
pip install kornia
pip install joblib==1.2.0